export const typeIcons: Record<string, any> = {
    normal: require("@/assets/icons/normal.svg"),
    fire: require("@/assets/icons/fire.svg"),
    water: require("@/assets/icons/water.svg"),
    electric: require("@/assets/icons/electric.svg"),
    grass: require("@/assets/icons/grass.svg"),
    ice: require("@/assets/icons/ice.svg"),
    fighting: require("@/assets/icons/fighting.svg"),
    poison: require("@/assets/icons/poison.svg"),
    ground: require("@/assets/icons/ground.svg"),
    flying: require("@/assets/icons/flying.svg"),
    psychic: require("@/assets/icons/psychic.svg"),
    bug: require("@/assets/icons/bug.svg"),
    rock: require("@/assets/icons/rock.svg"),
    ghost: require("@/assets/icons/ghost.svg"),
    dragon: require("@/assets/icons/dragon.svg"),
    dark: require("@/assets/icons/dark.svg"),
    steel: require("@/assets/icons/steel.svg"),
    fairy: require("@/assets/icons/fairy.svg"),
};